from turtle import *
from random import *

def immeuble(largeur, nb, color_facade, color_fenetre1, color_fenetre2):
    colormode(255)
    def facade():
        fillcolor(color_facade)
        begin_fill()
        for i in range (2) :
            forward(largeur*2)
            left(90)
            forward(largeur)
            left(90)
        end_fill()
        
        def fenetre():
            up()
            fillcolor(color_fenetre1)
            forward(largeur/5)
            left(90)
            begin_fill()
            forward(largeur/4)
            right(90)
            forward(largeur/6)
            left(90)
            forward(largeur/6)
            left(90)
            forward(largeur/6)
            left(90)
            forward(largeur/6)
            end_fill()
            forward(largeur/4)
            left(270)
            forward(largeur/5)
            left(180)
            down()

        fenetre()
        def fenetre2():
            up()
            forward(largeur+largeur/2)            
            fillcolor(color_fenetre2)
            forward(largeur/5)
            left(90)
            begin_fill()
            forward(largeur/4)
            right(90)
            forward(largeur/6)
            left(90)
            forward(largeur/6)
            left(90)
            forward(largeur/6)
            left(90)
            forward(largeur/6)
            end_fill()
            forward(largeur/4)
            left(270)
            forward(largeur/2)
            forward(largeur/2)
            forward(largeur/2)
            forward(largeur/5)
            left(180)
            down()
        fenetre2()
    position = [pos()[0], pos()[1]]    
    facade()
    def porte():
        forward(largeur)
        fillcolor("brown")
        begin_fill()
        left(90)
        forward(largeur/2)
        right(90)
        forward(largeur/4)
        right(90)
        forward(largeur/2)
        right(90)
        forward(largeur/4)
        end_fill()
        forward(largeur)  
        right(180) 
    porte()
    def nb_etages():
            for nb_etages in range(nb - 1) :
                left(90)
                forward(largeur)
                right(90)
                facade()
    nb_etages()
    goto(position[0], position[1])
    return largeur