import turtle as voiture
 
def voiture1(color: int):

    voiture.colormode(255)

    # Code pour créer le fuselage de la voiture
    voiture.color(color)
    voiture.fillcolor(color)
    voiture.penup()
    voiture.begin_fill()
    voiture.forward(370)
    voiture.left(90)
    voiture.forward(50)
    voiture.left(90)
    voiture.forward(370)
    voiture.left(90)
    voiture.forward(50)
    voiture.end_fill()
    voiture.left(90)
    
    
    # Code pour créer les fenêtres de cette dernière
    voiture.penup()
    voiture.left(90)
    voiture.forward(50)
    voiture.right(90)
    voiture.forward(100)
    voiture.pendown()
    voiture.setheading(45)
    voiture.forward(70)
    voiture.setheading(0)
    voiture.forward(100)
    voiture.setheading(-45)
    voiture.forward(70)
    voiture.setheading(90)
    voiture.penup()
    voiture.right(90)
    voiture.forward(-100)
    voiture.pendown()
    voiture.left(90)
    voiture.forward(49.50)    
    
    # Code pour créer les roues de cette automobile
    voiture.penup()
    voiture.forward(-108.99)
    voiture.right(90)
    voiture.forward(-1 * (99.5 + 10))
    voiture.pendown()
    voiture.color("red")
    voiture.fillcolor("red")
    voiture.begin_fill()
    voiture.circle(20)
    voiture.end_fill()
    voiture.penup()
    voiture.forward(300 - 89.49)
    voiture.pendown()
    voiture.color("red")
    voiture.fillcolor("red")
    voiture.begin_fill()
    voiture.circle(20)
    voiture.end_fill()